### ISSUE TITLE
verify if ASUS ZenPad is running Chrome webstore kiosk app or fspmarshall's kiosk fork

### ISSUE THREAD

**Issue by ryantanaka** [erdl/inactive-survey_display_template#1]
**fspmarshall's kiosk fork**

https://github.com/fspmarshall/kiosk

**Comment by carlosparadis** [comment]
Add here the fact we also need to know if it is running Forrest app, if we can automate the power on and off by comparing the commit Forrest did editing the code!

**Comment by ryantanaka** [comment]
The ZenPad is running the application from the Google Play Store. In the "Play Store -> My Apps & Games -> Installed" section, the Kiosk Browser application shows up. If he had done his own installation, I shouldn't be able to see it in the "Installed" section of the Play Store matching the most recent version.

**Comment by carlosparadis** [comment]
Thank you. I guess the next step is to figure out the options on turning it off from the Google Play store then (if we can pay a fee to permanently allow to power it off or on) and if we can use that version for research. 

Since I am not sure if we are keeping or not the kiosk project on Github, as it seems we are not using, can you create another issue on this project indicating the new task so we keep the discussion on the new issue? Also, please post a comment here with the link to the issue and this issue link on the new one so we can trace it back in the future.

**Comment by ryantanaka** [comment]
Okay, I've created the new issue: https://github.com/erdl/survey_display_local/issues/3

**Comment by carlosparadis** [comment]
Alright, I guess this issue is done then, I am closing it.
